plugins {
    id 'java'
    id 'io.micronaut.application' version '5.0.2'
}

group = 'ru'
version = '1.0-SNAPSHOT'

ext {
    lombokVersion = '1.18.48'
    mapstructVersion = '1.6.3'
}

repositories {
    mavenCentral()
}

micronaut {
    version = '5.0.2'
    runtime 'netty'
    testRuntime 'junit5'
    processing {
        incremental true
        annotations 'ru.*'
    }
}

application {
    mainClass = 'ru.Main'
}

dependencies {
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    annotationProcessor 'io.micronaut.serde:micronaut-serde-processor'
    annotationProcessor 'io.micronaut.data:micronaut-data-processor'

    compileOnly "org.projectlombok:lombok:${lombokVersion}"

    implementation 'io.micronaut:micronaut-runtime'
    implementation 'io.micronaut.data:micronaut-data-hibernate-jpa'
    implementation 'io.micronaut.sql:micronaut-jdbc-hikari'
    implementation 'io.micronaut.serde:micronaut-serde-jackson'
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"

    runtimeOnly 'ch.qos.logback:logback-classic'
    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly 'org.yaml:snakeyaml'

    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    testAnnotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'io.micronaut.test:micronaut-test-junit5'
    testImplementation 'io.micronaut:micronaut-http-client'
    testImplementation 'org.mockito:mockito-core:5.20.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.20.0'
    testImplementation 'org.testcontainers:junit-jupiter:1.21.3'
    testImplementation 'org.testcontainers:postgresql:1.21.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
